use_frameworks!

target 'LatoFont_Example' do
  pod 'LatoFont', :path => '../'

  target 'LatoFont_Tests' do
    inherit! :search_paths

    
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.0'
          end
      end
  end
end
